development:
  adapter: google_pubsub
  project: "franks-test-project-for-yea"
  keyfile: "service-account.json"
  topic: "action_cable"
  subscription: "action_cable"


test:
  adapter: async

production:
  adapter: async
